//! Prints one encoded trace to stdout, so a real receiver can judge the encoder.
//!
//! The point is to keep the encoder and its golden fixtures from sharing an author: a fixture
//! generated by the code under test cannot find a bug in it. Pipe this into a collector and see
//! whether what arrives is what was meant:
//!
//! ```sh
//! cargo run -q -p pessimal_usage --example emit_trace \
//!     | scripts/otlp-trace-probe.py --stdin http://localhost:4318
//! ```

use chrono::Utc;
use pessimal_usage::attribute::{BackendKind, DeviceClass, HttpStatusClass, Outcome, Platform};
use pessimal_usage::resource::{Service, UsageResource};
use pessimal_usage::span::{TraceId, UsageSpan, UsageTrace};
use uuid::Uuid;

fn main() {
    let resource = UsageResource::new(
        Service::Client,
        Platform::Ios,
        DeviceClass::Phone,
        Uuid::now_v7(),
        "0.1.0",
        Some(26),
        "18.4.1",
    );

    let started = Utc::now();
    let mut trace = UsageTrace::new(TraceId::new());
    let root = trace.record(
        UsageSpan::ClientPoll {
            outcome: Outcome::Partial,
            backend: BackendKind::Signoz,
            hosts: 12,
            rules: 3,
            alerts_firing: 1,
        },
        None,
        started,
        started + chrono::Duration::milliseconds(412),
    );
    trace.record(
        UsageSpan::ClientPlan {
            requests_planned: 20,
        },
        Some(root),
        started,
        started + chrono::Duration::microseconds(180),
    );
    trace.record(
        UsageSpan::ClientGather {
            outcome: Outcome::Ok,
            status_class: HttpStatusClass::of(200),
            series_returned: 24,
        },
        Some(root),
        started + chrono::Duration::milliseconds(2),
        started + chrono::Duration::milliseconds(390),
    );
    // The failure half of a partial poll: one backend request that never produced a status.
    trace.record(
        UsageSpan::ClientGather {
            outcome: Outcome::Unreachable,
            status_class: None,
            series_returned: 0,
        },
        Some(root),
        started + chrono::Duration::milliseconds(2),
        started + chrono::Duration::milliseconds(402),
    );
    trace.record(
        UsageSpan::ClientFold {
            outcome: Outcome::Partial,
            alerts_firing: 1,
        },
        Some(root),
        started + chrono::Duration::milliseconds(402),
        started + chrono::Duration::milliseconds(411),
    );

    let body = pessimal_usage::export_trace_request(&resource, &[trace]);
    println!(
        "{}",
        serde_json::to_string_pretty(&body).expect("serialisable")
    );
}
